language: cpp
env:
  global:
    - DEPS=""
matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      env:
        - DEPS="${DEPS} llvm@4"
        - LLVM_DIR=/usr/local/opt/llvm@4/lib/cmake/llvm/
        - ARGS=-V
#    - os: osx
#      compiler: clang
#      osx_image: xcode8
#      env:
#        - DEPS="${DEPS} llvm@4"
#        - LLVM_DIR=/usr/local/opt/llvm@4/lib/cmake/llvm/
#        - ARGS=-V
    - os: linux
      compiler: g++
      root: required
      dist: trusty
      group: deprecated-2017Q4
      services:
        - docker
      env:
        - DIST=xenial
        - ARGS=-V
    - os: linux
      compiler: g++
      root: required
      dist: trusty
      group: deprecated-2017Q4
      services:
        - docker
      env:
        - DIST=xllvm4
        - ARGS=-V

install:
  - if [ $TRAVIS_OS_NAME = osx   ]; then brew update && brew install -v ${DEPS} && find /usr/local/opt/llvm@4/ | grep cmake; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then cd docker/build &&  docker build . -f ./${DIST}.Dockerfile -t hobbes:build; cd -; fi

script:
  - if [ $TRAVIS_OS_NAME = osx   ]; then mkdir build && cd build/ && cmake .. && make && make test; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then docker run -it -v ${PWD}:/src hobbes:build; fi

branches:
  only:
    - master
    - travis
